/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pt.uma.ctesp.ficha8;

import java.awt.Color;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author joaogouveia
 */
public class Main extends javax.swing.JFrame {

    private double currentTempC = Math.random() * 31 + 12;
    private double currentTempF = currentTempC * 1.8 + 32;
    private double desiredTemp = currentTempC;
    private double currentHum = (int) (Math.random() * 100 + 5);
    private double desiredHum = currentHum;
    private boolean on = false;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.jLabelDate.setText(new Date() + "");
        this.jTextAreaLog.setEditable(false);
        this.jTextAreaLog.setForeground(Color.red);
        jLabelCurrentTemp.setText(String.format("%.2f", currentTempC) + " ºC");
        jLabelDesiredTemp.setText(String.format("%.2f", desiredTemp) + " ºC");
        this.jLabelCurrentHum.setText(currentHum + " %");
        this.jLabelDesiredHum.setText(desiredHum + " %");
        simulateTemperature();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabelCurrentTempLabel = new javax.swing.JLabel();
        jLabelCurrentTemp = new javax.swing.JLabel();
        jLabelDesiredTempLabel = new javax.swing.JLabel();
        jLabelDesiredTemp = new javax.swing.JLabel();
        jButtonTempDecrease = new javax.swing.JButton();
        jButtonTempIncrease = new javax.swing.JButton();
        jButtonConvertToF = new javax.swing.JButton();
        jButtonConvertToC = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelCurrentHumLabel = new javax.swing.JLabel();
        jLabelDesiredHumLabel = new javax.swing.JLabel();
        jLabelCurrentHum = new javax.swing.JLabel();
        jLabelDesiredHum = new javax.swing.JLabel();
        jButtonHumDecrease = new javax.swing.JButton();
        jButtonHumIncrease = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelDate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaLog = new javax.swing.JTextArea();
        jButtonON = new javax.swing.JButton();
        jButtonOFF = new javax.swing.JButton();
        jLabelStatus = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelCurrentTempLabel.setText("Current Temp:");

        jLabelCurrentTemp.setText("jLabelCurrentTemp");

        jLabelDesiredTempLabel.setText("Desired Temp:");

        jLabelDesiredTemp.setText("jLabelDesiredTemp");

        jButtonTempDecrease.setText("-");
        jButtonTempDecrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTempDecreaseActionPerformed(evt);
            }
        });

        jButtonTempIncrease.setText("+");
        jButtonTempIncrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTempIncreaseActionPerformed(evt);
            }
        });

        jButtonConvertToF.setText("F");
        jButtonConvertToF.setPreferredSize(new java.awt.Dimension(40, 37));
        jButtonConvertToF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertToFActionPerformed(evt);
            }
        });

        jButtonConvertToC.setText("C");
        jButtonConvertToC.setPreferredSize(new java.awt.Dimension(40, 37));
        jButtonConvertToC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertToCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonTempDecrease, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonTempIncrease, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonConvertToF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonConvertToC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelCurrentTempLabel)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelCurrentTemp))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelDesiredTempLabel)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelDesiredTemp)))
                        .addContainerGap(19, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCurrentTempLabel)
                    .addComponent(jLabelCurrentTemp))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDesiredTempLabel)
                    .addComponent(jLabelDesiredTemp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTempDecrease, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTempIncrease, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConvertToF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConvertToC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabelCurrentHumLabel.setText("Current Humidity:");

        jLabelDesiredHumLabel.setText("Desired Humidity:");

        jLabelCurrentHum.setText("jLabelCurrentHumidity");

        jLabelDesiredHum.setText("jLabelDesireHumidity");

        jButtonHumDecrease.setText("-");
        jButtonHumDecrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHumDecreaseActionPerformed(evt);
            }
        });

        jButtonHumIncrease.setText("+");
        jButtonHumIncrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHumIncreaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelCurrentHumLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCurrentHum))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelDesiredHumLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDesiredHum))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonHumDecrease, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonHumIncrease, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCurrentHumLabel)
                    .addComponent(jLabelCurrentHum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDesiredHumLabel)
                    .addComponent(jLabelDesiredHum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHumDecrease, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHumIncrease, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabelDate.setText("jLabelDate");

        jTextAreaLog.setColumns(20);
        jTextAreaLog.setRows(5);
        jScrollPane1.setViewportView(jTextAreaLog);

        jButtonON.setText("ON");
        jButtonON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonONActionPerformed(evt);
            }
        });

        jButtonOFF.setText("OFF");
        jButtonOFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOFFActionPerformed(evt);
            }
        });

        jLabelStatus.setText("jLabelStatus");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonOFF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabelStatus)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jLabelDate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelDate)
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButtonON)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonOFF)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTempDecreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTempDecreaseActionPerformed
        this.desiredTemp -= 0.5;
        jLabelDesiredTemp.setText(String.format("%.2f", desiredTemp) + " ºC");
        this.jTextAreaLog.append("Desired temperature decreased " + 0.5 + "\n");

    }//GEN-LAST:event_jButtonTempDecreaseActionPerformed

    private void jButtonTempIncreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTempIncreaseActionPerformed
        this.desiredTemp += 0.5;
        jLabelDesiredTemp.setText(String.format("%.2f", desiredTemp) + " ºC");
        this.jTextAreaLog.append("Desired temperature increased " + 0.5 + "\n");
    }//GEN-LAST:event_jButtonTempIncreaseActionPerformed

    private void jButtonHumDecreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHumDecreaseActionPerformed
        this.desiredHum -= 5;
        this.jLabelDesiredHum.setText(desiredHum + " %");
        this.jTextAreaLog.append("Desired Humididy decreased " + 5 + "\n");
    }//GEN-LAST:event_jButtonHumDecreaseActionPerformed

    private void jButtonHumIncreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHumIncreaseActionPerformed
        this.desiredHum += 5;
        this.jLabelDesiredHum.setText(desiredHum + " %");
        this.jTextAreaLog.append("Desired Humididy increased " + 5 + "\n");
    }//GEN-LAST:event_jButtonHumIncreaseActionPerformed

    private void jButtonConvertToFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertToFActionPerformed
        jLabelCurrentTemp.setText(String.format("%.2f", currentTempF) + " ºF");
    }//GEN-LAST:event_jButtonConvertToFActionPerformed

    private void jButtonConvertToCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertToCActionPerformed
        jLabelCurrentTemp.setText(String.format("%.2f", currentTempC) + " ºC");
    }//GEN-LAST:event_jButtonConvertToCActionPerformed

    private void jButtonONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonONActionPerformed
        this.on = true;
        jLabelStatus.setText("Heating ON!");
        controlTemperature();
    }//GEN-LAST:event_jButtonONActionPerformed

    private void jButtonOFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOFFActionPerformed
        this.on = false;
        jLabelStatus.setText("Heating OFF!");
    }//GEN-LAST:event_jButtonOFFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConvertToC;
    private javax.swing.JButton jButtonConvertToF;
    private javax.swing.JButton jButtonHumDecrease;
    private javax.swing.JButton jButtonHumIncrease;
    private javax.swing.JButton jButtonOFF;
    private javax.swing.JButton jButtonON;
    private javax.swing.JButton jButtonTempDecrease;
    private javax.swing.JButton jButtonTempIncrease;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabelCurrentHum;
    private javax.swing.JLabel jLabelCurrentHumLabel;
    private javax.swing.JLabel jLabelCurrentTemp;
    private javax.swing.JLabel jLabelCurrentTempLabel;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelDesiredHum;
    private javax.swing.JLabel jLabelDesiredHumLabel;
    private javax.swing.JLabel jLabelDesiredTemp;
    private javax.swing.JLabel jLabelDesiredTempLabel;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextAreaLog;
    // End of variables declaration//GEN-END:variables

    private void simulateTemperature() {
        Timer t = new Timer();
        TimerTask tt = new TimerTask() {
            @Override
            public void run() {
                if (Math.round(Math.random() * (100 - 0)) <= 30) {
                    currentTempC -= 0.5;
                    currentTempF = currentTempC * 1.8 + 32;
                    jLabelCurrentTemp.setText(String.format("%.2f", currentTempC) + "ºC");
                }
            }
        };
        t.scheduleAtFixedRate(tt, 0, 5000);
    }

    private void controlTemperature() {
        Timer t = new Timer();
        TimerTask tt = new TimerTask() {
            @Override
            public void run() {
                if ( (currentTempC == desiredTemp) && (currentHum == desiredHum) || (on == false)) {
                    on = false;
                    jLabelStatus.setText("Heating OFF!");
                    t.cancel();
                } else if ( (currentTempC < desiredTemp) || (currentHum < desiredHum)) {
                    currentTempC += 0.5;
                    jTextAreaLog.append("Temperature increased " + 5 + "\n");
                    jLabelCurrentTemp.setText(String.format("%.2f", currentTempC) + " ºC");
                } else {
                    currentTempC -= 0.5;
                    jLabelCurrentTemp.setText(String.format("%.2f", currentTempC) + " ºC");
                }
            }
        };
        t.scheduleAtFixedRate(tt, 0, 3000);
    }
}
